--PROMPT
--PROMPT CREATING TABLE LOGG
--PROMPT ===================
--PROMPT
CREATE TABLE LOGG
(
  XDD VARCHAR(2500)
)
;

--PROMPT
--PROMPT CREATING TABLE SEG_D_USUARIO_CARGO
--PROMPT ==================================
--PROMPT
CREATE TABLE SEG_D_USUARIO_CARGO
(
  ID_USUARIO_CARGO NUMERIC(20) PRIMARY KEY IDENTITY(1,1) NOT NULL,
  ID_USUARIO       NUMERIC(20),
  ID_CARGO         NUMERIC(20),
  ID_OFICINA       NUMERIC(20),
  ID_SEDE         NUMERIC(20),
  FLG_JEFE         CHAR(1),
  FLG_ESTADO       INT DEFAULT 1,
  USU_CREACION     VARCHAR(50),
  FEC_CREACION     DATE DEFAULT GETDATE(),
  IP_CREACION      VARCHAR(50),
  USU_MODIFICACION VARCHAR(50),
  FEC_MODIFICACION DATE,
  IP_MODIFICACION  VARCHAR(50)
)
;

--PROMPT
--PROMPT CREATING TABLE SEG_M_CARGO
--PROMPT ==========================
--PROMPT
CREATE TABLE SEG_M_CARGO
(
  ID_CARGO         NUMERIC(20) primary key IDENTITY(1,10) NOT NULL ,
  DESC_CARGO       VARCHAR(150),
  FLG_ESTADO       INT DEFAULT 1,
  USU_CREACION     VARCHAR(50),
  FEC_CREACION     DATE DEFAULT GETDATE(),
  IP_CREACION      VARCHAR(50),
  USU_MODIFICACION VARCHAR(50),
  FEC_MODIFICACION DATE,
  IP_MODIFICACION  VARCHAR(50)
)
;
ALTER TABLE SEG_M_CARGO
  ADD CONSTRAINT PK_C_ID_CARGO PRIMARY KEY (ID_CARGO);

--PROMPT
--PROMPT CREATING TABLE SEG_M_ENTIDAD
--PROMPT ============================
--PROMPT

CREATE TABLE SEG_M_ENTIDAD
(
  ID_ENTIDAD       NUMERIC(20) primary key IDENTITY(1,4),
  DESC_ENTIDAD    VARCHAR(200),
  SIGLA_ENTIDAD    VARCHAR(250),
  FLG_ESTADO       INT DEFAULT 1,
  USU_CREACION     VARCHAR(50),
  FEC_CREACION     DATE DEFAULT GETDATE(),
  IP_CREACION      VARCHAR(50),
  USU_MODIFICACION VARCHAR(50),
  FEC_MODIFICACION DATE,
  IP_MODIFICACION  VARCHAR(50)
)
;

--PROMPT
--PROMPT CREATING TABLE SEG_M_OFICINA
--PROMPT ============================
CREATE TABLE SEG_M_OFICINA
(
  ID_OFICINA         NUMERIC(20)  primary key IDENTITY(1,1) NOT NULL,
  ID_ENTIDAD         NUMERIC(20) DEFAULT 1,
  ID_SEDE            NUMERIC(20), 
  ID_OFICINA_PADRE   NUMERIC(20),
  DESC_CORTA_OFICINA VARCHAR(150),
  DESC_OFICINA       VARCHAR(250),
  SIGLA_OFICINA      VARCHAR(150),
  VDS                DATE,
  FLG_ESTADO         INT DEFAULT 1,
  USU_CREACION       VARCHAR(50),
  FEC_CREACION       DATE DEFAULT GETDATE(),
  IP_CREACION        VARCHAR(50),
  USU_MODIFICACION   VARCHAR(50),
  FEC_MODIFICACION   DATE,
  IP_MODIFICACION    VARCHAR(50)
)
;


ALTER TABLE SEG_M_OFICINA
  ADD CONSTRAINT PK_O_ID_OFICINA PRIMARY KEY (ID_OFICINA);

--PROMPT
--PROMPT CREATING TABLE SEG_M_PERFIL
--PROMPT ===========================
--
CREATE TABLE SEG_M_PERFIL
(
  ID_PERFIL        NUMERIC(20)primary key identity(1,1) NOT NULL,
  ID_SISTEMA       NUMERIC(20) NOT NULL,
  DESC_PERFIL      VARCHAR(150) NOT NULL,
  FLG_COMBO        INT,
  FLG_ESTADO       INT DEFAULT 1,
  USU_CREACION     VARCHAR(50),
  FEC_CREACION     DATE DEFAULT GETDATE(),
  IP_CREACION      VARCHAR(50),
  USU_MODIFICACION VARCHAR(50),
  FEC_MODIFICACION DATE,
  IP_MODIFICACION  VARCHAR(50)
)
;

--PROMPT
--PROMPT CREATING TABLE SEG_M_SISTEMA
--PROMPT ============================
--PROMPT
CREATE TABLE SEG_M_SISTEMA
(
  ID_SISTEMA       NUMERIC(20),
  CODIGO_SISTEMA     VARCHAR(200),
  DESC_SISTEMA     VARCHAR(150),
  CODIGO_IMAGEN     VARCHAR(200),
  FLG_ESTADO       INT DEFAULT 1,
  USU_CREACION     VARCHAR(50),
  FEC_CREACION     DATE DEFAULT GETDATE(),
  IP_CREACION      VARCHAR(50),
  USU_MODIFICACION VARCHAR(50),
  FEC_MODIFICACION DATE,
  IP_MODIFICACION  VARCHAR(50)
)
;

--PROMPT
--PROMPT CREATING TABLE SEG_M_USUARIO
--PROMPT ============================
--PROMPT
CREATE TABLE SEG_M_USUARIO
(
  ID_USUARIO       NUMERIC(20) PRIMARY KEY IDENTITY(1,1) NOT NULL,
  ID_ENTIDAD       NUMERIC(20) ,
  COD_USUARIO      VARCHAR(150),
  CLAVE_USUARIO    VARCHAR(150) DEFAULT 123,
  NOMBRE_USUARIO   VARCHAR(200),
  APE_PATERNO      VARCHAR(200),
  APE_MATERNO      VARCHAR(200),
  DNI              VARCHAR(12),
  CORREO     VARCHAR(100),
  CELULAR    VARCHAR(100),
  TELEFONO   VARCHAR(100),
  REGIMEN VARCHAR(200), 
  FLG_ESTADO       INT DEFAULT 1,
  USU_CREACION     VARCHAR(50),
  FEC_CREACION     DATE DEFAULT GETDATE(),
  IP_CREACION      VARCHAR(50),
  USU_MODIFICACION VARCHAR(50),
  FEC_MODIFICACION DATE,
  IP_MODIFICACION  VARCHAR(50)
)
;


--PROMPT
--PROMPT CREATING TABLE SEG_R_USUARIO_PERFIL
--PROMPT ===================================
--PROMPT


CREATE TABLE SEG_R_USUARIO_PERFIL
(
  ID_USUARIO_PERFIL NUMERIC(20) PRIMARY KEY IDENTITY(1,1) NOT NULL,
  ID_SISTEMA        NUMERIC(20) NOT NULL,
  ID_USUARIO        NUMERIC(20) NOT NULL,
  ID_PERFIL         NUMERIC(20) NOT NULL,
  ID_OFICINA        NUMERIC(20) NOT NULL,
  ID_CARGO          NUMERIC(20),
  ID_SEDE          NUMERIC(20),
  FEC_ACTIVACION          DATE,
  FEC_DESACTIVACION       DATE,
  FLG_ESTADO       INT DEFAULT 1,
  USU_CREACION     VARCHAR(50),
  FEC_CREACION     DATE DEFAULT GETDATE(),
  IP_CREACION      VARCHAR(50),
  USU_MODIFICACION VARCHAR(50),
  FEC_MODIFICACION DATE,
  IP_MODIFICACION  VARCHAR(50)

)
;

--PROMPT
--PROMPT CREATING TABLE TRA_D_DOCUMENTO_ADJUNTO
--PROMPT ======================================
--PROMPT
CREATE TABLE TRA_D_DOCUMENTO_ADJUNTO
(
  ID_DOCUMENTO_ADJUNTO NUMERIC(20) NOT NULL,
  ID_DOCUMENTO         NUMERIC(20),
  NOMBRE_ARCHIVO       VARCHAR(500),
  CODIGO_ARCHIVO       VARCHAR(500),
  PESO_ARCHIVO         NUMERIC,
  EXTENSION_ARCHIVO    VARCHAR(100),
  FLG_FIRMA            CHAR(1) DEFAULT 0,
  FLG_ESTADO           CHAR(1) DEFAULT 1,
  USU_CREACION         VARCHAR(50),
  FEC_CREACION         DATE DEFAULT GETDATE(),
  IP_CREACION          VARCHAR(50),
  USU_MODIFICACION     VARCHAR(50),
  FEC_MODIFICACION     DATE,
  IP_MODIFICACION      VARCHAR(50)
)
;

--PROMPT
--PROMPT CREATING TABLE TRA_D_DOCUMENTO_ANEXO
--PROMPT ====================================
--PROMPT
CREATE TABLE TRA_D_DOCUMENTO_ANEXO
(
  ID_DOCUMENTO_ANEXO NUMERIC(20) NOT NULL,
  NRO_CUT            VARCHAR(20),
  ID_DOCUMENTO_PADRE NUMERIC(20),
  ID_DOCUMENTO_HIJO  NUMERIC(20),
  FLG_ANEXADO        CHAR(1) DEFAULT 0,
  FLG_ESTADO         CHAR(1) DEFAULT 1,
  USU_CREACION       VARCHAR(50),
  FEC_CREACION       DATE DEFAULT GETDATE(),
  IP_CREACION        VARCHAR(50),
  USU_MODIFICACION   VARCHAR(50),
  FEC_MODIFICACION   DATE,
  IP_MODIFICACION    VARCHAR(50)
)
;

--PROMPT
--PROMPT CREATING TABLE TRA_D_DOCUMENTO_DESTINO
--PROMPT ======================================
--PROMPT
CREATE TABLE TRA_D_DOCUMENTO_DESTINO
(
  ID_DOCUMENTO_DESTINO INTEGER NOT NULL,
  ID_DOCUMENTO         INTEGER,
  ID_ENTIDAD           INTEGER,
  OFICINA              VARCHAR(150),
  RUBRICA              VARCHAR(30),
  REMITENTE            VARCHAR(150),
  CARGO                VARCHAR(150),
  DIRECCION            VARCHAR(500),
  FLG_MGD              CHAR(1) DEFAULT 1,
  FLG_DOMICILIO        CHAR(1) DEFAULT 1,
  FLG_ESTADO           CHAR(1) DEFAULT 1,
  USU_CREACION         VARCHAR(50),
  FEC_CREACION         DATE DEFAULT GETDATE(),
  IP_CREACION          VARCHAR(50),
  USU_MODIFICACION     VARCHAR(50),
  FEC_MODIFICACION     DATE,
  IP_MODIFICACION      VARCHAR(50)
)
;

--PROMPT
--PROMPT CREATING TABLE TRA_D_DOCUMENTO_MOVIMIENTO
--PROMPT =========================================
--PROMPT
CREATE TABLE TRA_D_DOCUMENTO_MOVIMIENTO
(
  ID_DOCUMENTO_MOVIMIENTO NUMERIC(20) NOT NULL,
  ID_DOCUMENTO            NUMERIC(20),
  ID_ESTADO_DOCUMENTO     NUMERIC(20),
  MOVIMIENTO              VARCHAR(4000),
  ID_USUARIO              NUMERIC(20),
  ID_OFICINA              NUMERIC(20),
  ID_CARGO                NUMERIC(20),
  FLG_ESTADO              CHAR(1) DEFAULT 1,
  USU_CREACION            VARCHAR(50),
  FEC_CREACION            DATE DEFAULT GETDATE(),
  IP_CREACION             VARCHAR(50),
  USU_MODIFICACION        VARCHAR(50),
  FEC_MODIFICACION        DATE,
  IP_MODIFICACION         VARCHAR(50)
)
;

--PROMPT
--PROMPT CREATING TABLE TRA_D_DOCUMENTO_OFICINA
--PROMPT ======================================
--PROMPT
CREATE TABLE TRA_D_DOCUMENTO_OFICINA
(
  ID_DOCUMENTO_OFICINA NUMERIC(20) NOT NULL,
  ID_DOCUMENTO         NUMERIC(20),
  ID_OFICINA           NUMERIC(20),
  ID_USUARIO           NUMERIC(20),
  ID_CARGO             NUMERIC(20),
  FLG_CARGO            CHAR(1) DEFAULT 0,
  COD_CARGO            VARCHAR(150),
  FEC_CARGO            DATE,
  FLG_ESTADO           CHAR(1) DEFAULT 1,
  USU_CREACION         VARCHAR(50),
  FEC_CREACION         DATE DEFAULT GETDATE(),
  IP_CREACION          VARCHAR(50),
  USU_MODIFICACION     VARCHAR(50),
  FEC_MODIFICACION     DATE,
  IP_MODIFICACION      VARCHAR(50)
)
;

--PROMPT
--PROMPT CREATING TABLE TRA_D_DOCUMENTO_USUARIO
--PROMPT ======================================
--PROMPT
CREATE TABLE TRA_D_DOCUMENTO_USUARIO
(
  ID_DOCUMENTO_USUARIO NUMERIC(20),
  ID_DOCUMENTO         NUMERIC(20),
  ID_USUARIO           NUMERIC(20),
  ID_OFICINA           NUMERIC(20),
  ID_CARGO             NUMERIC(20),
  ID_TAREA             NUMERIC(20),
  NRO_PRIORIDAD        INTEGER,
  FLG_CUMPLIDO         CHAR(1) DEFAULT 0,
  FEC_CUMPLIDO         DATE,
  FLG_RECHAZADO        CHAR(1) DEFAULT 0,
  FLG_EDITAR           CHAR(1),
  FLG_PERMITIDO        CHAR(1) DEFAULT 1,
  FLG_EDITO            CHAR(1) DEFAULT 0,
  NOMBRE_USUARIO       VARCHAR(150),
  NOMBRE_OFICINA       VARCHAR(150),
  DASDSA               DATE,
  FLG_ESTADO           CHAR(1) DEFAULT 1,
  USU_CREACION         VARCHAR(100),
  FEC_CREACION         DATE DEFAULT GETDATE(),
  IP_CREACION          VARCHAR(20),
  USU_MODIFICACION     VARCHAR(100),
  FEC_MODIFICACION     DATE,
  IP_MODIFICACION      VARCHAR(20)
)
;

--PROMPT
--PROMPT CREATING TABLE TRA_D_PLANTILLA_CAMPO
--PROMPT ====================================
--PROMPT
CREATE TABLE TRA_D_PLANTILLA_CAMPO
(
  ID_PLANTILLA_CAMPO INTEGER,
  ID_PLANTILLA       INTEGER,
  ID_CAMPO           INTEGER,
  ORDEN              NUMERIC,
  FLG_ESTADO         INT DEFAULT 1,
  USU_CREACION       VARCHAR(50),
  FEC_CREACION       DATE DEFAULT GETDATE(),
  IP_CREACION        VARCHAR(50),
  USU_MODIFICACION   VARCHAR(50),
  FEC_MODIFICACION   DATE,
  IP_MODIFICACION    VARCHAR(50)
)
;

--PROMPT
--PROMPT CREATING TABLE TRA_L_CABECERA
--PROMPT =============================
--PROMPT
	CREATE TABLE TRA_M_CABECERA
	(
	  ID_CABECERA      NUMERIC(20) PRIMARY KEY IDENTITY(1,1) NOT NULL,
	  ID_TIPO_DOCUMENTO NUMERIC(20)NULL, 
	  NOMBRE_ANIO      VARCHAR(3000),
	  NOMBRE_DECENIO   VARCHAR(3000),
	  CODIGO_IMAGEN    VARCHAR(3000),
	  NOMBRE_IMAGEN    VARCHAR(3000),
	  EXTENSION_IMAGEN VARCHAR(3000),
	  FLG_POSICION      int,
	  FLG_ESTADO       INT DEFAULT 1,
	  USU_CREACION     VARCHAR(50),
	  FEC_CREACION     DATE DEFAULT GETDATE(),
	  IP_CREACION      VARCHAR(50),
	  USU_MODIFICACION VARCHAR(50),
	  FEC_MODIFICACION DATE,
	  IP_MODIFICACION  VARCHAR(50)
	)
	;

--PROMPT
--PROMPT CREATING TABLE TRA_L_CAMPO
--PROMPT ==========================
--PROMPT
CREATE TABLE TRA_L_CAMPO
(
  ID_CAMPO         INTEGER,
  ID_CAMPO_PADRE   INTEGER,
  DESC_CAMPO       VARCHAR(500),
  CODIGO_CAMPO     VARCHAR(500),
  FLG_ESTADO       INT DEFAULT 1,
  USU_CREACION     VARCHAR(50),
  FEC_CREACION     DATE DEFAULT GETDATE(),
  IP_CREACION      VARCHAR(50),
  USU_MODIFICACION VARCHAR(50),
  FEC_MODIFICACION DATE,
  IP_MODIFICACION  VARCHAR(50)
)
;

--PROMPT
--PROMPT CREATING TABLE TRA_L_ENTIDADES
--PROMPT ==============================
--PROMPT
CREATE TABLE TRA_L_ENTIDADES
(
  ID_ENTIDAD          NUMERIC(20) PRIMARY KEY IDENTITY(1,1) NOT NULL, 
  DESC_ENTIDAD        VARCHAR(150),
  RUC_ENTIDAD         VARCHAR(11),
  ABREVIACION_ENTIDAD VARCHAR(150),
  DIRECCION_ENTIDAD   VARCHAR(50),
  FLG_ESTADO         INT DEFAULT 1,
  USU_CREACION        VARCHAR(50),
  FEC_CREACION        DATE DEFAULT GETDATE(),
  IP_CREACION         VARCHAR(50),
  USU_MODIFICACION    VARCHAR(50),
  FEC_MODIFICACION    DATE,
  IP_MODIFICACION     VARCHAR(50)
)
;


--PROMPT
--PROMPT CREATING TABLE TRA_L_ESTADO_DOCUMENTO
--PROMPT =====================================
--PROMPT
CREATE TABLE TRA_L_ESTADO_DOCUMENTO
(
  ID_ESTADO_DOCUMENTO   NUMERIC(20) NOT NULL,
  DESC_ESTADO_DOCUMENTO VARCHAR(200),
  FLG_ESTADO            CHAR(1) DEFAULT 1,
  USU_CREACION          VARCHAR(50),
  FEC_CREACION          DATE DEFAULT GETDATE(),
  IP_CREACION           VARCHAR(50),
  USU_MODIFICACION      VARCHAR(50),
  FEC_MODIFICACION      DATE,
  IP_MODIFICACION       VARCHAR(50)
)
;

--PROMPT
--PROMPT CREATING TABLE TRA_L_TAREA
--PROMPT ==========================
--PROMPT
  CREATE TABLE TRA_L_TAREA
(
  ID_TAREA         NUMERIC(20) primary  key identity(1,1) ,
  DESC_TAREA       VARCHAR(150),
  FLG_COMBO        CHAR(1) default 1 not null,
  FLG_ACCION       CHAR(1) default 0 not null,
  FLG_FINALIZA     CHAR(1) default 0 not null,
  FLG_ESTADO       INT DEFAULT 1,
  USU_CREACION     VARCHAR(50),
  FEC_CREACION     DATE DEFAULT GETDATE(),
  IP_CREACION      VARCHAR(50),
  USU_MODIFICACION VARCHAR(50),
  FEC_MODIFICACION DATE,
  IP_MODIFICACION  VARCHAR(50)
)
;


--PROMPT
--PROMPT CREATING TABLE TRA_L_TIPO_DOCUMENTO
--PROMPT ===================================
--PROMPT
CREATE TABLE TRA_L_TIPO_DOCUMENTO
(
  ID_TIPO_DOCUMENTO      NUMERIC(20) primary key identity(1,1) NOT NULL,
  ID_TIPO_DOCUMENTO_PIDE VARCHAR(2),
  DESC_TIPO_DOCUMENTO    VARCHAR(200),
  SIGLA_TIPO_DOCUMENTO   VARCHAR(100),
  FLG_MGD                int 0,
  FLG_ESTADO             int DEFAULT 1,
  USU_CREACION           VARCHAR(50),
  FEC_CREACION           DATE DEFAULT GETDATE(),
  IP_CREACION            VARCHAR(50),
  USU_MODIFICACION       VARCHAR(50),
  FEC_MODIFICACION       DATE,
  IP_MODIFICACION        VARCHAR(50)
)
;

--PROMPT
--PROMPT CREATING TABLE TRA_M_CORRELATIVO
--PROMPT ================================
--PROMPT
CREATE TABLE TRA_M_CORRELATIVO
(
  ID_CORRELATIVO    NUMERIC(20),
  ID_TIPO_DOCUMENTO NUMERIC(20),
  ID_OFICINA        NUMERIC(20),
  ID_PERFIL         NUMERIC(20),
  N_CORRELATIVO     NUMERIC(20),
  N_ANIO            NUMERIC(20)
)
;

--PROMPT
--PROMPT CREATING TABLE TRA_M_CUT
--PROMPT ========================
--PROMPT
CREATE TABLE TRA_M_CUT
(
  ID_CUT           NUMERIC(20) NOT NULL,
  NRO_CUT          NUMERIC(20),
  ID_ANIO          NUMERIC(10),
  FLG_ESTADO       CHAR(1) DEFAULT 1,
  USU_CREACION     VARCHAR(50),
  FEC_CREACION     DATE DEFAULT GETDATE(),
  IP_CREACION      VARCHAR(50),
  USU_MODIFICACION VARCHAR(50),
  FEC_MODIFICACION DATE,
  IP_MODIFICACION  VARCHAR(50)
)
;
ALTER TABLE TRA_M_CUT
  ADD CONSTRAINT PK_C_ID_CUT PRIMARY KEY (ID_CUT);
ALTER TABLE TRA_M_CUT
  ADD CONSTRAINT UK_C_ID_ANIO UNIQUE (ID_ANIO);

--PROMPT
--PROMPT CREATING TABLE TRA_M_DOCUMENTO
--PROMPT ==============================
--PROMPT
CREATE TABLE TRA_M_DOCUMENTO
(
  ID_DOCUMENTO          NUMERIC(20) NOT NULL,
  NRO_CUT               VARCHAR(20) NOT NULL,
  ID_TIPO               INTEGER DEFAULT 1,
  ID_TIPO_DOCUMENTO     NUMERIC(20),
  ID_FLUJO              INTEGER DEFAULT 1,
  ID_ESTADO_DOCUMENTO   INTEGER,
  ASUNTO                VARCHAR(2000),
  REFERENCIA            VARCHAR(2000),
  CORRELATIVO_DOCUMENTO NUMERIC(20),
  NRO_DOCUMENTO         VARCHAR(500),
  COD_ARCHIVO           VARCHAR(100),
  NOMBRE_ARCHIVO        VARCHAR(200),
  EXTENSION_ARCHIVO     VARCHAR(50),
  CLAVE_FIRMA           VARCHAR(20),
  FEC_FIRMA             DATE,
  COD_ARCHIVO_FIRMADO   VARCHAR(100),
  FLG_FIRMA             CHAR(1) DEFAULT 0,
  FLG_PROYECTADO        CHAR(1),
  FLG_ZIP               CHAR(1) DEFAULT 0,
  ID_USUARIO            NUMERIC(20) NOT NULL,
  ID_OFICINA            NUMERIC(20) NOT NULL,
  ID_CARGO              NUMERIC(20) NOT NULL,
  FLG_ESTADO            CHAR(1) DEFAULT 1,
  USU_CREACION          VARCHAR(50),
  FEC_CREACION          DATE DEFAULT GETDATE(),
  IP_CREACION           VARCHAR(50),
  USU_MODIFICACION      VARCHAR(50),
  FEC_MODIFICACION      DATE,
  IP_MODIFICACION       VARCHAR(50)
)
;
 
ALTER TABLE TRA_M_DOCUMENTO
  ADD CONSTRAINT PK_D_ID_DOCUMENTO PRIMARY KEY (ID_DOCUMENTO);

--PROMPT
--PROMPT CREATING TABLE TRA_M_PLANTILLA
--PROMPT ==============================
--PROMPT
CREATE TABLE TRA_M_PLANTILLA
(
  ID_PLANTILLA        INTEGER,
  ID_TIPO_DOCUMENTO   INTEGER,
  DESC_PLANTILLA      VARCHAR(500),
  CODIGO_DOCUMENTO    VARCHAR(4000),
  NOMBRE_DOCUMENTO    VARCHAR(4000),
  EXTENSION_DOCUMENTO VARCHAR(4000),
  FLG_ESTADO          INT DEFAULT 1,
  USU_CREACION        VARCHAR(50),
  FEC_CREACION        DATE DEFAULT GETDATE(),
  IP_CREACION         VARCHAR(50),
  USU_MODIFICACION    VARCHAR(50),
  FEC_MODIFICACION    DATE,
  IP_MODIFICACION     VARCHAR(50)
)
;



CREATE TABLE SEG_D_OFICINA_FILTROS
(
  ID_OFICINA_FILTRO    NUMERIC(20) PRIMARY KEY IDENTITY(1,1) NOT NULL ,
  ID_OFICINA_PERMISO    NUMERIC(20)    NULL ,
  ID_OFICINA    NUMERIC(20)   NULL ,
  ID_TAREA    NUMERIC(20)   NULL ,
  ID_USUARIO    NUMERIC(20)   NULL ,
  FLG_ESTADO          INT DEFAULT 1,
  USU_CREACION        VARCHAR(50),
  FEC_CREACION        DATE DEFAULT GETDATE(),
  IP_CREACION         VARCHAR(50),
  USU_MODIFICACION    VARCHAR(50),
  FEC_MODIFICACION    DATE,
  IP_MODIFICACION     VARCHAR(50)
)

GO


CREATE TABLE SEG_M_OFICINA_PERMISO
(
  ID_OFICINA_PERMISO    NUMERIC(20) IDENTITY(1,1) PRIMARY KEY NOT NULL ,
  ID_OFICINA_DESTINO    NUMERIC(20) NOT NULL,
  FLG_ESTADO          INT DEFAULT 1,
  USU_CREACION        VARCHAR(50),
  FEC_CREACION        DATE DEFAULT GETDATE(),
  IP_CREACION         VARCHAR(50),
  USU_MODIFICACION    VARCHAR(50),
  FEC_MODIFICACION    DATE,
  IP_MODIFICACION     VARCHAR(50)
)
;



CREATE TABLE SEG_M_SEDE
(
  ID_SEDE    NUMERIC(20) IDENTITY(1,1) PRIMARY KEY NOT NULL ,
  DESC_SEDE     VARCHAR(200) NOT NULL,
  DIRECCION   VARCHAR(200)  NULL,
  TELEFONO    VARCHAR(200) NULL,
  CORREO    VARCHAR(200) NULL,
  PAGINAWEB_ENTIDAD   VARCHAR(200) NULL,
  PAGINAWEB_SECTOR    VARCHAR(200) NULL,
  ID_DEPARTAMENTO VARCHAR(20), 
  ID_PROVINCIA VARCHAR(20), 
  ID_DISTRITO VARCHAR(20), 
  FLG_ESTADO          INT DEFAULT 1,
  USU_CREACION        VARCHAR(50),
  FEC_CREACION        DATE DEFAULT GETDATE(),
  IP_CREACION         VARCHAR(50),
  USU_MODIFICACION    VARCHAR(50),
  FEC_MODIFICACION    DATE,
  IP_MODIFICACION     VARCHAR(50)
)
;

CREATE TABLE SEG_M_TIPO_RECURSO
(
  ID_TIPORECURSO    NUMERIC(20) PRIMARY KEY NOT NULL ,
  COD_TIPORECURSO     VARCHAR(200) NOT NULL,
  NOM_TIPORECURSO   VARCHAR(200)  NULL,
  DESC_TIPORECURSO    VARCHAR(200) NULL,
  FEC_ACTIV_TIPORECURSO    DATE,
  FEC_DESCACTIV_TIPORECURSO   DATE,
  FLG_ESTADO          INT DEFAULT 1,
  USU_CREACION        VARCHAR(50),
  FEC_CREACION        DATE DEFAULT GETDATE(),
  IP_CREACION         VARCHAR(50),
  USU_MODIFICACION    VARCHAR(50),
  FEC_MODIFICACION    DATE,
  IP_MODIFICACION     VARCHAR(50)
)



CREATE TABLE [dbo].[SEG_D_SISTEMAS_PERFIL_MODULO](
	[ID_SISTEMAS_PERFIL_MODULO] [numeric](20, 0) IDENTITY(1,1) NOT NULL,
	[ID_SISTEMA] [numeric](20, 0) NOT NULL,
	[ID_PERFIL] [numeric](20, 0) NOT NULL,
	[ID_MODULO] [numeric](20, 0) NOT NULL,
	[FLG_ESTADO] INT NULL DEFAULT '1',
	[USU_CREACION] [varchar](50) NULL,
	[FEC_CREACION] [date] NULL,
	[IP_CREACION] [varchar](50) NULL,
	[USU_MODIFICACION] [varchar](50) NULL,
	[FEC_MODIFICACION] [date] NULL,
	[IP_MODIFICACION] [varchar](50) NULL

)



CREATE TABLE SEG_D_SISTEMAS_MODULO
(
  ID_SISTEMA_MODULO    NUMERIC(20) PRIMARY KEY IDENTITY(1,1) NOT NULL ,
  ID_SISTEMA    NUMERIC(20)  NOT NULL ,
  ID_TIPO_MODULO    NUMERIC(20)  NOT NULL ,
  ID_SISTEMA_MODULO_PADRE    NUMERIC(20)   NULL ,
  ID_A    VARCHAR(200)  NULL ,
  ID_LI    VARCHAR(200)    NULL ,
  IMAGEN    VARCHAR(200)   NULL ,
  URL_MODULO     VARCHAR(200)    NULL ,
  DESC_MODULO    VARCHAR(200)   NULL ,
  ORDEN    INT   NULL ,
  NIVEL    INT  NULL ,
  FLG_ESTADO         INT DEFAULT 1,
  USU_CREACION        VARCHAR(50),
  FEC_CREACION        DATE DEFAULT GETDATE(),
  IP_CREACION         VARCHAR(50),
  USU_MODIFICACION    VARCHAR(50),
  FEC_MODIFICACION    DATE,
  IP_MODIFICACION     VARCHAR(50)
)





CREATE TABLE SEG_M_PROFESIONALES
(
  ID_PROFESIONAL    NUMERIC(20) PRIMARY KEY IDENTITY(1,1) NOT NULL ,
  DESC_PROFESIONAL    VARCHAR(500)   NULL ,
  ID_ENTIDAD   NUMERIC(20)   NULL ,
  FLG_ESTADO          INT DEFAULT 1,
  USU_CREACION        VARCHAR(50),
  FEC_CREACION        DATE DEFAULT GETDATE(),
  IP_CREACION         VARCHAR(50),
  USU_MODIFICACION    VARCHAR(50),
  FEC_MODIFICACION    DATE,
  IP_MODIFICACION     VARCHAR(50)
)




CREATE TABLE SEG_D_PROFESIONALES
(
  ID_DET_PROFESIONAL    NUMERIC(20) PRIMARY KEY IDENTITY(1,1) NOT NULL ,
  ID_PROFESIONAL    NUMERIC(20)  NOT NULL ,
  ID_USUARIO    NUMERIC(20)  NOT NULL ,
  ID_OFICINA    NUMERIC(20)  NOT NULL ,
  ID_CARGO    NUMERIC(20)  NOT NULL ,
  FLG_ESTADO          INT DEFAULT 1,
  USU_CREACION        VARCHAR(50),
  FEC_CREACION        DATE DEFAULT GETDATE(),
  IP_CREACION         VARCHAR(50),
  USU_MODIFICACION    VARCHAR(50),
  FEC_MODIFICACION    DATE,
  IP_MODIFICACION     VARCHAR(50)
)



CREATE TABLE TRA_M_MOTIVOS_FIRMA
(
  ID_MOTIVO_FIRMA        NUMERIC(20) PRIMARY KEY IDENTITY(1,1) NOT NULL ,
  DESC_MOTIVO_FRIMA     VARCHAR(500)   NULL ,
  FLG_ESTADO          INT DEFAULT 1,
  USU_CREACION        VARCHAR(50),
  FEC_CREACION        DATE DEFAULT GETDATE(),
  IP_CREACION         VARCHAR(50),
  USU_MODIFICACION    VARCHAR(50),
  FEC_MODIFICACION    DATE,
  IP_MODIFICACION     VARCHAR(50)
)

CREATE TABLE TRA_M_PIE_PAGINA
	(
	  ID_PIE_PAGINA      NUMERIC(20) PRIMARY KEY IDENTITY(1,1) NOT NULL,
	  ID_TIPO_DOCUMENTO NUMERIC(20)NULL, 
	  FLG_DISCLAIMER      INT, 
	  FLG_DEFAULT         INT, 
	  FLG_SEDE               INT,  
	  FLG_ESTADO       INT DEFAULT 1,  
	  USU_CREACION     VARCHAR(50),
	  FEC_CREACION     DATE DEFAULT GETDATE(),
	  IP_CREACION      VARCHAR(50),
	  USU_MODIFICACION VARCHAR(50),
	  FEC_MODIFICACION DATE,
	  IP_MODIFICACION  VARCHAR(50)
	);




 
 CREATE TABLE TRA_D_PIE_PAGINA
	(
	  ID_DET_PIE_PAGINA     NUMERIC(20) PRIMARY KEY IDENTITY(1,1) NOT NULL,
	  ID_PIE_PAGINA      NUMERIC(20) NULL,
	  FLG_POSICION        INT, 
	  CODIGO_IMAGEN    VARCHAR(3000),
	  NOMBRE_IMAGEN    VARCHAR(3000),
	  EXTENSION_IMAGEN VARCHAR(3000),
	  FLG_ESTADO       INT DEFAULT 1,
	  USU_CREACION     VARCHAR(50),
	  FEC_CREACION     DATE DEFAULT GETDATE(),
	  IP_CREACION      VARCHAR(50),
	  USU_MODIFICACION VARCHAR(50),
	  FEC_MODIFICACION DATE,
	  IP_MODIFICACION  VARCHAR(50)
	);
	
	
	
	CREATE TABLE [dbo].[SEG_M_USUARIO_PERMISO](
	[ID_USUARIO_PERMISO] [numeric](20, 0) IDENTITY(1,1) NOT NULL,
	[ID_USUARIO] [numeric](20, 0) NOT NULL,
	[ID_PERFIL] [numeric](20, 0) NOT NULL,
	ID_OFICINA NUMERIC(20) 
	[FLG_ESTADO] [int] NULL,
	[USU_CREACION] [varchar](50) NULL,
	[FEC_CREACION] [datetime] NULL,
	[IP_CREACION] [varchar](50) NULL,
	[USU_MODIFICACION] [varchar](50) NULL,
	[FEC_MODIFICACION] [datetime] NULL,
	[IP_MODIFICACION] [varchar](50) NULL,
  ); 
  
  
    
  CREATE TABLE [dbo].[SEG_D_USUARIO_FILTROS](
	[ID_USUARIO_FILTRO] [numeric](20, 0) IDENTITY(1,1) NOT NULL,
	[ID_USUARIO_PERMISO] [numeric](20, 0) NULL,
	[ID_USUARIO] [numeric](20, 0) NULL,
	[ID_OFICINA] [numeric](20, 0) NULL,
	[FLG_ACCION] [int] NULL,
	[FLG_CONSULTA] [int] NULL,
	FEC_INICIO  DATE, 
	FEC_FIN   DATE , 
	[FLG_ESTADO] [int] NULL DEFAULT ((1)),
	[USU_CREACION] [varchar](50) NULL,
	[FEC_CREACION] [datetime] NULL DEFAULT (getdate()),
	[IP_CREACION] [varchar](50) NULL,
	[USU_MODIFICACION] [varchar](50) NULL,
	[FEC_MODIFICACION] [datetime] NULL,
	[IP_MODIFICACION] [varchar](50) NULL
	) ; 
 
 
 CREATE TABLE [dbo].[SEG_M_UBIGEO](
	[COD_UBIGEO] [char](6) NOT NULL,
	[COD_UBIGEO_PADRE] [char](6) NULL,
	[DESC_UBIGEO] [varchar](60) NULL,
	[TIP_ZONA_GEO] [char](1) NULL,
	[FLG_ESTADO] [int] NULL,
	[USU_CREACION] [varchar](50) NULL,
	[IP_CREACION] [varchar](50) NULL,
	[FEC_CREACION] [datetime] NULL,
	[USU_MODIFICACION] [varchar](50) NULL,
	[IP_MODIFICACION] [varchar](50) NULL,
	[FEC_MODIFICACION] [datetime] NULL
) ; 