--prompt
--prompt Creating view V_TIPO_DOCUMENTO
--prompt ==============================
--prompt
CREATE   VIEW V_TIPO_DOCUMENTO AS
SELECT TOP 9999999
      TD.ID_TIPO_DOCUMENTO,
      TD.DESC_TIPO_DOCUMENTO,
      TD.SIGLA_TIPO_DOCUMENTO,
      TD.FLG_MGD
  FROM
      TRA_L_TIPO_DOCUMENTO TD
  ORDER BY
      TD.DESC_TIPO_DOCUMENTO ASC;
 GO
--prompt
--prompt Creating view V_DOCUMENTO
--prompt =========================
--prompt
CREATE   VIEW V_DOCUMENTO AS
SELECT TOP 9999999
     D.ID_DOCUMENTO,
     D.NRO_CUT,
     D.ID_TIPO,
     CASE WHEN D.ID_TIPO = 1 THEN
         'DIGITAL'
     ELSE
         'FISICO'
     END  DESC_TIPO,
     D.ID_TIPO_DOCUMENTO,
     TD.DESC_TIPO_DOCUMENTO,
     D.ASUNTO,
     D.REFERENCIA,
     D.ID_ESTADO_DOCUMENTO,
     ED.DESC_ESTADO_DOCUMENTO,
     '' DESTINOS,
     CAST(D.CORRELATIVO_DOCUMENTO AS VARCHAR) CORRELATIVO_DOCUMENTO,
     D.NRO_DOCUMENTO NUMERO_DOCUMENTO,
     CONVERT(VARCHAR,D.FEC_FIRMA, 109) FECHA_FIRMA,
     D.CLAVE_FIRMA,
     D.FLG_ESTADO,
     D.ID_USUARIO,
     D.ID_OFICINA,
     D.USU_CREACION,
     D.FEC_CREACION,
     ISNULL(CONVERT(VARCHAR,D.FEC_CREACION, 109), '-') STR_FEC_CREACION,
     ISNULL(D.IP_CREACION, '-') IP_CREACION,
     ISNULL(D.USU_MODIFICACION, '-') USU_MODIFICACION,
     D.FEC_MODIFICACION,
     ISNULL(CONVERT(VARCHAR,D.FEC_MODIFICACION, 109), '-') STR_FEC_MODIFICACION,
     ISNULL(D.IP_MODIFICACION, '-') IP_MODIFICACION
 FROM
     TRA_M_DOCUMENTO D
     INNER JOIN TRA_L_ESTADO_DOCUMENTO ED ON ED.ID_ESTADO_DOCUMENTO = D.ID_ESTADO_DOCUMENTO
     INNER JOIN V_TIPO_DOCUMENTO TD ON TD.ID_TIPO_DOCUMENTO = D.ID_TIPO_DOCUMENTO;
	 GO
--prompt
--prompt Creating view V_DOCUMENTO_ANEXO
--prompt ===============================
--prompt
CREATE   VIEW V_DOCUMENTO_ANEXO AS
SELECT TOP 9999999
     0 ID_DOCUMENTO_ANEXO,
     D.ID_DOCUMENTO ID_DOCUMENTO_PADRE,
     D.ID_DOCUMENTO ID_DOCUMENTO_HIJO,
     D.NRO_CUT,
     CASE WHEN D.ID_TIPO = 1 THEN
         'DIGITAL'
     ELSE
         'FISICO'
     END  DESC_TIPO,
     D.ID_TIPO_DOCUMENTO,
     TD.DESC_TIPO_DOCUMENTO,
     D.ASUNTO,
     D.ID_ESTADO_DOCUMENTO,
     ED.DESC_ESTADO_DOCUMENTO,
     0 ID_DOCUMENTO
 FROM
     TRA_M_DOCUMENTO D
     INNER JOIN TRA_L_ESTADO_DOCUMENTO ED ON ED.ID_ESTADO_DOCUMENTO = D.ID_ESTADO_DOCUMENTO
     INNER JOIN V_TIPO_DOCUMENTO TD ON TD.ID_TIPO_DOCUMENTO = D.ID_TIPO_DOCUMENTO
 WHERE
     ID_DOCUMENTO NOT IN (SELECT A.ID_DOCUMENTO_HIJO FROM TRA_D_DOCUMENTO_ANEXO A);
	 GO
--promptG
--prompt Creating view V_DOCUMENTO_ANEXO_HIJO
--prompt ====================================
--prompt
CREATE  VIEW V_DOCUMENTO_ANEXO_HIJO AS
SELECT TOP 9999999
     A.ID_DOCUMENTO_ANEXO,
     A.ID_DOCUMENTO_PADRE,
     A.ID_DOCUMENTO_HIJO,
     D.NRO_CUT,
     CASE WHEN D.ID_TIPO = 1 THEN
         'DIGITAL'
     ELSE
         'FISICO'
     END  DESC_TIPO,
     D.ID_TIPO_DOCUMENTO,
     TD.DESC_TIPO_DOCUMENTO,
     D.ASUNTO,
     D.ID_ESTADO_DOCUMENTO,
     ED.DESC_ESTADO_DOCUMENTO,
     0 ID_DOCUMENTO
 FROM
     TRA_D_DOCUMENTO_ANEXO A
     INNER JOIN TRA_M_DOCUMENTO D ON D.ID_DOCUMENTO = A.ID_DOCUMENTO_HIJO
     INNER JOIN TRA_L_ESTADO_DOCUMENTO ED ON ED.ID_ESTADO_DOCUMENTO = D.ID_ESTADO_DOCUMENTO
     INNER JOIN V_TIPO_DOCUMENTO TD ON TD.ID_TIPO_DOCUMENTO = D.ID_TIPO_DOCUMENTO;
	 GO
--prompt
--prompt Creating view V_DOCUMENTO_ASIGNADO
--prompt ==================================
--prompt
CREATE   VIEW V_DOCUMENTO_ASIGNADO AS
SELECT TOP 9999999
     D.ID_DOCUMENTO,
     D.NRO_CUT,
     D.ID_TIPO,
     CASE WHEN D.ID_TIPO = 1 THEN
         'DIGITAL'
     ELSE
         'FISICO'
     END  DESC_TIPO,
     D.ID_TIPO_DOCUMENTO,
     TD.DESC_TIPO_DOCUMENTO,
     D.ASUNTO,
     D.REFERENCIA,
     D.ID_ESTADO_DOCUMENTO,
     ED.DESC_ESTADO_DOCUMENTO,
     '' DESTINOS,
     CAST(D.CORRELATIVO_DOCUMENTO AS VARCHAR) CORRELATIVO_DOCUMENTO,
     D.NRO_DOCUMENTO NUMERO_DOCUMENTO, 
     CONVERT(VARCHAR,D.FEC_FIRMA, 109) FECHA_FIRMA,
     D.CLAVE_FIRMA,
     D.FLG_ESTADO,

     DU.ID_DOCUMENTO_USUARIO,
     DU.ID_USUARIO ID_USUARIO_ASIGNADO,
     DU.ID_OFICINA ID_OFICINA_ASIGNADO,
     DU.ID_CARGO,
     DU.FLG_CUMPLIDO,
     DU.FLG_PERMITIDO,
     T.ID_TAREA,
     T.DESC_TAREA,

     D.ID_USUARIO,
     D.ID_OFICINA,
     D.USU_CREACION,
     D.FEC_CREACION,
     ISNULL(CONVERT(VARCHAR,D.FEC_CREACION, 109), '-') STR_FEC_CREACION,
     ISNULL(D.IP_CREACION, '-') IP_CREACION,
     ISNULL(D.USU_MODIFICACION, '-') USU_MODIFICACION,
     D.FEC_MODIFICACION,
     ISNULL(CONVERT(VARCHAR,D.FEC_MODIFICACION, 109), '-') STR_FEC_MODIFICACION,
     ISNULL(D.IP_MODIFICACION, '-') IP_MODIFICACION
 FROM
     TRA_M_DOCUMENTO D
     INNER JOIN TRA_L_ESTADO_DOCUMENTO ED ON ED.ID_ESTADO_DOCUMENTO = D.ID_ESTADO_DOCUMENTO
     INNER JOIN V_TIPO_DOCUMENTO TD ON TD.ID_TIPO_DOCUMENTO = D.ID_TIPO_DOCUMENTO
     INNER JOIN TRA_D_DOCUMENTO_USUARIO DU ON DU.ID_DOCUMENTO = D.ID_DOCUMENTO
     INNER JOIN TRA_L_TAREA T ON T.ID_TAREA = DU.ID_TAREA;
	 GO
--prompt
--prompt Creating view V_DOCUMENTO_DESTINO
--prompt =================================
--prompt
CREATE   VIEW V_DOCUMENTO_DESTINO AS
SELECT TOP 9999999
     D.ID_DOCUMENTO,
     D.NRO_CUT,
     D.ID_TIPO,
     CASE WHEN D.ID_TIPO = 1 THEN
         'DIGITAL'
     ELSE
         'FISICO'
     END  DESC_TIPO,
     D.ID_TIPO_DOCUMENTO,
     TD.DESC_TIPO_DOCUMENTO,
     D.ASUNTO,
     D.REFERENCIA,
     D.ID_ESTADO_DOCUMENTO,
     ED.DESC_ESTADO_DOCUMENTO,
     '' DESTINOS,
     CAST (D.CORRELATIVO_DOCUMENTO AS VARCHAR) CORRELATIVO_DOCUMENTO,
     D.NRO_DOCUMENTO NUMERO_DOCUMENTO,
     CONVERT(VARCHAR,D.FEC_FIRMA, 109) FECHA_FIRMA,
     D.CLAVE_FIRMA,
     D.FLG_ESTADO,

     DO.ID_DOCUMENTO_OFICINA,
     DO.ID_USUARIO ID_USUARIO_OFICINA,
     DO.ID_OFICINA ID_OFICINA_OFICINA,
     DO.ID_CARGO,
     DO.FLG_CARGO,

     D.ID_USUARIO,
     D.ID_OFICINA,
     D.USU_CREACION,
     D.FEC_CREACION,
     ISNULL(CONVERT(VARCHAR,D.FEC_CREACION, 109), '-') STR_FEC_CREACION,
     ISNULL(D.IP_CREACION, '-') IP_CREACION,
     ISNULL(D.USU_MODIFICACION, '-') USU_MODIFICACION,
     D.FEC_MODIFICACION,
     ISNULL(CONVERT(VARCHAR,D.FEC_MODIFICACION, 109), '-') STR_FEC_MODIFICACION,
     ISNULL(D.IP_MODIFICACION, '-') IP_MODIFICACION
 FROM
     TRA_M_DOCUMENTO D
     INNER JOIN TRA_D_DOCUMENTO_OFICINA DO ON DO.ID_DOCUMENTO = D.ID_DOCUMENTO
     INNER JOIN TRA_L_ESTADO_DOCUMENTO ED ON ED.ID_ESTADO_DOCUMENTO = D.ID_ESTADO_DOCUMENTO
     INNER JOIN V_TIPO_DOCUMENTO TD ON TD.ID_TIPO_DOCUMENTO = D.ID_TIPO_DOCUMENTO
     INNER JOIN SEG_M_OFICINA O ON DO.ID_OFICINA = O.ID_OFICINA
     --INNER JOIN TRA_L_TAREA T ON T.ID_TAREA = DU.ID_TAREA
;
GO
--prompt
--prompt Creating view V_SEG_USUARIO
--prompt ===========================
--prompt
CREATE  VIEW V_SEG_USUARIO AS
SELECT TOP 9999999
      UC.ID_USUARIO_CARGO,
      UP.ID_SISTEMA,
      UC.ID_OFICINA,
      O.DESC_OFICINA,
      UC.ID_USUARIO,
      UPPER(U.NOMBRE_USUARIO) NOMBRE_USUARIO,
      UC.ID_CARGO,
      CONCAT(UPPER(C.DESC_CARGO), ' - ' ,UPPER(P.DESC_PERFIL)) DESC_CARGO,
      P.ID_PERFIL,
      UPPER(P.DESC_PERFIL) DESC_PERFIL
  FROM
      SEG_D_USUARIO_CARGO UC
      INNER JOIN SEG_M_USUARIO U ON U.ID_USUARIO = UC.ID_USUARIO
      INNER JOIN SEG_M_OFICINA O ON O.ID_OFICINA = UC.ID_OFICINA
      INNER JOIN SEG_R_USUARIO_PERFIL UP ON UP.ID_USUARIO = UC.ID_USUARIO
                                            AND UP.ID_OFICINA = UC.ID_OFICINA
                                            AND UP.ID_CARGO = UC.ID_CARGO
      INNER JOIN SEG_M_CARGO C ON C.ID_CARGO = UC.ID_CARGO
      INNER JOIN SEG_M_PERFIL P ON P.ID_PERFIL = UP.ID_PERFIL
                                   AND UP.ID_SISTEMA = P.ID_SISTEMA
  ORDER BY
      C.DESC_CARGO ASC;


CREATE  VIEW V_USUARIO  AS 
SELECT
      U.ID_USUARIO,
      U.COD_USUARIO,
      UPPER(U.NOMBRE_USUARIO) NOMBRE_USUARIO,
      U.APE_PATERNO,
      U.APE_MATERNO,
      E.DESC_ENTIDAD,
      U.ID_ENTIDAD,

      CONCAT(U.NOMBRE_USUARIO , ' ' ,  U.APE_PATERNO , ' ' , U.APE_MATERNO) AS NOMBRES_COMPLETOS,
      U.DNI,
      U.TELEFONO,
      U.CELULAR,
      U.CORREO,
      U.CLAVE_USUARIO,
    /*  (SELECT
           LISTAGG( C.DESC_CARGO  + ' - ' ||  O.DESC_OFICINA,   ' ' || CHR(13)) WITHIN GROUP (ORDER BY UC.ID_USUARIO_CARGO)  --  ,  LISTAGG(S.DNOMBRE, ', ')   WITHIN GROUP (ORDER BY S.DDOCUMENTO)
       FROM
           SEG_D_USUARIO_CARGO UC
           INNER JOIN SEG_M_CARGO C ON C.ID_CARGO = UC.ID_CARGO
           INNER JOIN SEG_M_OFICINA O ON O.ID_OFICINA = UC.ID_OFICINA

       WHERE
           UC.ID_USUARIO = U.ID_USUARIO)*/ '' DESC_CARGO,

            U.FLG_ESTADO,
            U.USU_CREACION,       
			CONVERT(VARCHAR,U.FEC_CREACION, 103) FEC_CREACION,
            U.IP_CREACION,
            U.USU_MODIFICACION,
			CONVERT(VARCHAR,U.FEC_MODIFICACION, 103) FEC_MODIFICACION,
            U.IP_MODIFICACION


  FROM
      SEG_M_USUARIO U
        LEFT JOIN  SEG_M_ENTIDAD E ON E.ID_ENTIDAD = U.ID_ENTIDAD

  ORDER BY
      U.ID_USUARIO ASC

