CREATE TABLE SEG_M_SEDE
(
  ID_SEDE    NUMERIC(20) IDENTITY(1,1) PRIMARY KEY NOT NULL ,
  DESC_SEDE     VARCHAR(200) NOT NULL,
  DIRECCION   VARCHAR(200)  NULL,
  TELEFONO    VARCHAR(200) NULL,
  CORREO    VARCHAR(200) NULL,
  PAGINAWEB_ENTIDAD   VARCHAR(200) NULL,
  PAGINAWEB_SECTOR    VARCHAR(200) NULL,
  FLG_ESTADO          INT DEFAULT 1,
  USU_CREACION        VARCHAR(50),
  FEC_CREACION        DATE DEFAULT GETDATE(),
  IP_CREACION         VARCHAR(50),
  USU_MODIFICACION    VARCHAR(50),
  FEC_MODIFICACION    DATE,
  IP_MODIFICACION     VARCHAR(50)
)
;



CREATE TABLE SEG_M_PROFESIONALES
(
  ID_PROFESIONAL    NUMERIC(20) PRIMARY KEY IDENTITY(1,1) NOT NULL ,
  DESC_PROFESIONAL    VARCHAR(500)   NULL ,
  ID_ENTIDAD   NUMERIC(20)   NULL ,
  FLG_ESTADO          INT DEFAULT 1,
  USU_CREACION        VARCHAR(50),
  FEC_CREACION        DATE DEFAULT GETDATE(),
  IP_CREACION         VARCHAR(50),
  USU_MODIFICACION    VARCHAR(50),
  FEC_MODIFICACION    DATE,
  IP_MODIFICACION     VARCHAR(50)
); 

GO

CREATE TABLE TRA_M_MOTIVOS_FIRMA
(
  ID_MOTIVO_FIRMA        NUMERIC(20) PRIMARY KEY IDENTITY(1,1) NOT NULL ,
  DESC_MOTIVO_FRIMA     VARCHAR(500)   NULL ,
  FLG_ESTADO          INT DEFAULT 1,
  USU_CREACION        VARCHAR(50),
  FEC_CREACION        DATE DEFAULT GETDATE(),
  IP_CREACION         VARCHAR(50),
  USU_MODIFICACION    VARCHAR(50),
  FEC_MODIFICACION    DATE,
  IP_MODIFICACION     VARCHAR(50)
); 

GO

CREATE TABLE SEG_M_OFICINA_PERMISO
(
  ID_OFICINA_PERMISO    NUMERIC(20) IDENTITY(1,1) PRIMARY KEY NOT NULL ,
  ID_OFICINA_DESTINO    NUMERIC(20) NOT NULL,
  FLG_ESTADO          INT DEFAULT 1,
  USU_CREACION        VARCHAR(50),
  FEC_CREACION        DATE DEFAULT GETDATE(),
  IP_CREACION         VARCHAR(50),
  USU_MODIFICACION    VARCHAR(50),
  FEC_MODIFICACION    DATE,
  IP_MODIFICACION     VARCHAR(50)
)
;
GO



CREATE TABLE SEG_D_OFICINA_FILTROS
(
  ID_OFICINA_FILTRO    NUMERIC(20) PRIMARY KEY IDENTITY(1,1) NOT NULL ,
  ID_OFICINA_PERMISO    NUMERIC(20)    NULL ,
  ID_OFICINA    NUMERIC(20)   NULL ,
  ID_TAREA    NUMERIC(20)   NULL ,
  ID_USUARIO    NUMERIC(20)   NULL ,
  FLG_ESTADO          INT DEFAULT 1,
  USU_CREACION        VARCHAR(50),
  FEC_CREACION        DATE DEFAULT GETDATE(),
  IP_CREACION         VARCHAR(50),
  USU_MODIFICACION    VARCHAR(50),
  FEC_MODIFICACION    DATE,
  IP_MODIFICACION     VARCHAR(50)
); 
GO


create table TRA_D_ACCION
(
  ID_ACCION	        NUMERIC(20) PRIMARY KEY IDENTITY(1,1) not null,
  DESC_ACCION      VARCHAR(150) not null,
  FLG_ACCION       CHAR(1) default 0 not null,
  FLG_DERIVA       CHAR(1) default 1,
  FLG_ASGINA       CHAR(1) default 1,
  FLG_ESTADO       INT DEFAULT 1,
  USU_CREACION     VARCHAR(50),
  FEC_CREACION     DATE DEFAULT GETDATE(),
  IP_CREACION      VARCHAR(50),
  USU_MODIFICACION VARCHAR(50),
  FEC_MODIFICACION DATE,
  IP_MODIFICACION  VARCHAR(50)
)
;
GO 


CREATE TABLE SEG_D_SISTEMAS_MODULO
(
  ID_SISTEMA_MODULO    NUMERIC(20) PRIMARY KEY IDENTITY(1,1) NOT NULL ,
  ID_SISTEMA    NUMERIC(20)  NOT NULL ,
  ID_TIPO_MODULO    NUMERIC(20)  NOT NULL ,
  ID_SISTEMA_MODULO_PADRE    NUMERIC(20)   NULL ,
  ID_A    VARCHAR(200)  NULL ,
  ID_LI    VARCHAR(200)    NULL ,
  IMAGEN    VARCHAR(200)   NULL ,
  URL_MODULO     VARCHAR(200)    NULL ,
  DESC_MODULO    VARCHAR(200)   NULL ,
  ORDEN    INT   NULL ,
  NIVEL    INT  NULL ,
  FLG_ESTADO         INT DEFAULT 1,
  USU_CREACION        VARCHAR(50),
  FEC_CREACION        DATE DEFAULT GETDATE(),
  IP_CREACION         VARCHAR(50),
  USU_MODIFICACION    VARCHAR(50),
  FEC_MODIFICACION    DATE,
  IP_MODIFICACION     VARCHAR(50)
);
GO 


CREATE TABLE [dbo].[SEG_D_SISTEMAS_PERFIL_MODULO](
	[ID_SISTEMAS_PERFIL_MODULO] [numeric](20, 0) IDENTITY(1,1) NOT NULL,
	[ID_SISTEMA] [numeric](20, 0) NOT NULL,
	[ID_PERFIL] [numeric](20, 0) NOT NULL,
	[ID_MODULO] [numeric](20, 0) NOT NULL,
	[FLG_ESTADO] INT NULL DEFAULT '1',
	[USU_CREACION] [varchar](50) NULL,
	[FEC_CREACION] [date] NULL,
	[IP_CREACION] [varchar](50) NULL,
	[USU_MODIFICACION] [varchar](50) NULL,
	[FEC_MODIFICACION] [date] NULL,
	[IP_MODIFICACION] [varchar](50) NULL

); 

GO 



CREATE TABLE SEG_M_TIPO_RECURSO
(
  ID_TIPORECURSO    NUMERIC(20) PRIMARY KEY NOT NULL ,
  COD_TIPORECURSO     VARCHAR(200) NOT NULL,
  NOM_TIPORECURSO   VARCHAR(200)  NULL,
  DESC_TIPORECURSO    VARCHAR(200) NULL,
  FEC_ACTIV_TIPORECURSO    DATE,
  FEC_DESCACTIV_TIPORECURSO   DATE,
  FLG_ESTADO          INT DEFAULT 1,
  USU_CREACION        VARCHAR(50),
  FEC_CREACION        DATE DEFAULT GETDATE(),
  IP_CREACION         VARCHAR(50),
  USU_MODIFICACION    VARCHAR(50),
  FEC_MODIFICACION    DATE,
  IP_MODIFICACION     VARCHAR(50)
); 

GO


insert into SEG_M_TIPO_RECURSO (ID_TIPORECURSO, COD_TIPORECURSO, NOM_TIPORECURSO, DESC_TIPORECURSO, FEC_ACTIV_TIPORECURSO, FEC_DESCACTIV_TIPORECURSO, FLG_ESTADO, USU_CREACION, FEC_CREACION, USU_MODIFICACION, FEC_MODIFICACION)
values (2 ,'TIPOREC', 'ME', 'MENU', null, null, 1, null, null, null, null);
insert into SEG_M_TIPO_RECURSO (ID_TIPORECURSO, COD_TIPORECURSO, NOM_TIPORECURSO, DESC_TIPORECURSO, FEC_ACTIV_TIPORECURSO, FEC_DESCACTIV_TIPORECURSO, FLG_ESTADO, USU_CREACION, FEC_CREACION, USU_MODIFICACION, FEC_MODIFICACION)
values (5, 'TIPOREC', 'GM', 'GRUPO MENU', null, null, 1, null, null, null, null);
insert into SEG_M_TIPO_RECURSO (ID_TIPORECURSO, COD_TIPORECURSO, NOM_TIPORECURSO, DESC_TIPORECURSO, FEC_ACTIV_TIPORECURSO, FEC_DESCACTIV_TIPORECURSO, FLG_ESTADO, USU_CREACION, FEC_CREACION, USU_MODIFICACION, FEC_MODIFICACION)
values (7, 'TIPOREC', 'MES', 'MENU SIN GRUPO', null, null, 1, null, null, null, null);

GO 

insert into SEG_D_SISTEMAS_MODULO ( ID_SISTEMA, ID_TIPO_MODULO, ID_SISTEMA_MODULO_PADRE, ID_A, ID_LI, IMAGEN, URL_MODULO, DESC_MODULO, ORDEN, NIVEL, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values ( 1, 5, 0, null, 'liTInterno', 'clip-settings', null, 'Tramite Interno', 1, 1, '1', null, CAST('25-04-2021 14:20:29'as date), null, null, null, null);
insert into SEG_D_SISTEMAS_MODULO ( ID_SISTEMA, ID_TIPO_MODULO, ID_SISTEMA_MODULO_PADRE, ID_A, ID_LI, IMAGEN, URL_MODULO, DESC_MODULO, ORDEN, NIVEL, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values ( 1, 2, 1, 'aDocumento', 'liDocumento', null, null, 'Crear/Anular Documento', 2, 2, '1', null, CAST('25-04-2021 14:20:29'as date), null, null, null, null);
insert into SEG_D_SISTEMAS_MODULO ( ID_SISTEMA, ID_TIPO_MODULO, ID_SISTEMA_MODULO_PADRE, ID_A, ID_LI, IMAGEN, URL_MODULO, DESC_MODULO, ORDEN, NIVEL, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values ( 1, 2, 1, 'aDocumentoRevisar', 'liDocumentoRevisar', null, null, 'Revisar Documento', 3, 2, '1', null, CAST('25-04-2021 14:20:29'as date), null, null, null, null);
insert into SEG_D_SISTEMAS_MODULO ( ID_SISTEMA, ID_TIPO_MODULO, ID_SISTEMA_MODULO_PADRE, ID_A, ID_LI, IMAGEN, URL_MODULO, DESC_MODULO, ORDEN, NIVEL, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values ( 1, 2, 1, 'aDocumentoAprobar', 'liDocumentoAprobar', null, null, 'Aprobar Documento', 4, 2, '1', null, CAST('25-04-2021 14:20:29'as date), null, null, null, null);
insert into SEG_D_SISTEMAS_MODULO ( ID_SISTEMA, ID_TIPO_MODULO, ID_SISTEMA_MODULO_PADRE, ID_A, ID_LI, IMAGEN, URL_MODULO, DESC_MODULO, ORDEN, NIVEL, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values ( 1, 2, 1, 'aDocumentoVisar', 'liDocumentoVisar', null, null, 'Visar Documento', 5, 2, '1', null, CAST('25-04-2021 14:20:29'as date), null, null, null, null);
insert into SEG_D_SISTEMAS_MODULO ( ID_SISTEMA, ID_TIPO_MODULO, ID_SISTEMA_MODULO_PADRE, ID_A, ID_LI, IMAGEN, URL_MODULO, DESC_MODULO, ORDEN, NIVEL, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values ( 1, 2, 1, 'aDocumentoFirmar', 'liDocumentoFirmar', null, null, 'Firmar Documento', 6, 2, '1', null, CAST('25-04-2021 14:20:29'as date), null, null, null, null);
insert into SEG_D_SISTEMAS_MODULO ( ID_SISTEMA, ID_TIPO_MODULO, ID_SISTEMA_MODULO_PADRE, ID_A, ID_LI, IMAGEN, URL_MODULO, DESC_MODULO, ORDEN, NIVEL, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values ( 1, 2, 1, 'aDocumentoRecibir', 'liDocumentoRecibir', null, null, 'Recibir Documento', 7, 2, '1', null, CAST('25-04-2021 14:20:29'as date), null, null, null, null);
insert into SEG_D_SISTEMAS_MODULO ( ID_SISTEMA, ID_TIPO_MODULO, ID_SISTEMA_MODULO_PADRE, ID_A, ID_LI, IMAGEN, URL_MODULO, DESC_MODULO, ORDEN, NIVEL, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values ( 1, 5, 0, null, 'liReporte', 'clip-settings', null, 'Reportes', 8, 1, '1', null, CAST('25-04-2021 14:23:13'as date), null, null, null, null);
insert into SEG_D_SISTEMAS_MODULO ( ID_SISTEMA, ID_TIPO_MODULO, ID_SISTEMA_MODULO_PADRE, ID_A, ID_LI, IMAGEN, URL_MODULO, DESC_MODULO, ORDEN, NIVEL, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values ( 1, 2, 8, 'aReporte1', 'liReporte_1', null, null, 'Reporte 1', 9, 2, '1', null, CAST('25-04-2021 14:23:13'as date), null, null, null, null);
insert into SEG_D_SISTEMAS_MODULO ( ID_SISTEMA, ID_TIPO_MODULO, ID_SISTEMA_MODULO_PADRE, ID_A, ID_LI, IMAGEN, URL_MODULO, DESC_MODULO, ORDEN, NIVEL, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values ( 1, 5, 0, null, 'liAdministracion', 'clip-settings', null, 'Administración', 10, 1, '1', null, CAST('25-04-2021 14:26:27'as date), null, null, null, null);
insert into SEG_D_SISTEMAS_MODULO ( ID_SISTEMA, ID_TIPO_MODULO, ID_SISTEMA_MODULO_PADRE, ID_A, ID_LI, IMAGEN, URL_MODULO, DESC_MODULO, ORDEN, NIVEL, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values ( 1, 2, 10, 'aPerfil', 'liPerfil', null, null, 'Perfil', 11, 2, '1', null, CAST('25-04-2021 14:26:27'as date), null, null, null, null);
insert into SEG_D_SISTEMAS_MODULO ( ID_SISTEMA, ID_TIPO_MODULO, ID_SISTEMA_MODULO_PADRE, ID_A, ID_LI, IMAGEN, URL_MODULO, DESC_MODULO, ORDEN, NIVEL, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values ( 1, 2, 10, 'aEntidad', 'liEntidad', null, null, 'Entidad', 12, 2, '1', null, CAST('25-04-2021 14:26:27'as date), null, null, null, null);
insert into SEG_D_SISTEMAS_MODULO ( ID_SISTEMA, ID_TIPO_MODULO, ID_SISTEMA_MODULO_PADRE, ID_A, ID_LI, IMAGEN, URL_MODULO, DESC_MODULO, ORDEN, NIVEL, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values ( 1, 2, 10, 'aCargo', 'liCargo', null, null, 'Cargo', 13, 2, '1', null, CAST('25-04-2021 14:26:27'as date), null, null, null, null);
insert into SEG_D_SISTEMAS_MODULO ( ID_SISTEMA, ID_TIPO_MODULO, ID_SISTEMA_MODULO_PADRE, ID_A, ID_LI, IMAGEN, URL_MODULO, DESC_MODULO, ORDEN, NIVEL, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values ( 1, 2, 10, 'aOficina', 'liOficina', null, null, 'Oficina', 14, 2, '1', null, CAST('25-04-2021 14:26:27'as date), null, null, null, null);
insert into SEG_D_SISTEMAS_MODULO ( ID_SISTEMA, ID_TIPO_MODULO, ID_SISTEMA_MODULO_PADRE, ID_A, ID_LI, IMAGEN, URL_MODULO, DESC_MODULO, ORDEN, NIVEL, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values ( 1, 2, 10, 'aUsuario', 'liUsuario', null, null, 'Usuario', 15, 2, '1', null, CAST('25-04-2021 14:26:27'as date), null, null, null, null);
insert into SEG_D_SISTEMAS_MODULO ( ID_SISTEMA, ID_TIPO_MODULO, ID_SISTEMA_MODULO_PADRE, ID_A, ID_LI, IMAGEN, URL_MODULO, DESC_MODULO, ORDEN, NIVEL, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values ( 1, 2, 10, 'aSistemas', 'liSistemas', null, null, 'Sistemas', 16, 2, '1', null, CAST('25-04-2021 14:26:27'as date), null, null, null, null);

GO 





ALTER  VIEW [dbo].[V_USUARIO]  AS 
SELECT
      U.ID_USUARIO,
      U.COD_USUARIO,
      UPPER(U.NOMBRE_USUARIO) NOMBRE_USUARIO,
      U.APE_PATERNO,
      U.APE_MATERNO,
      E.DESC_ENTIDAD,
      U.ID_ENTIDAD,
     CONCAT(U.NOMBRE_USUARIO , ' ' ,  U.APE_PATERNO , ' ' , U.APE_MATERNO)AS NOMBRES_COMPLETOS,
      U.DNI,
      U.TELEFONO,
      U.CELULAR,
      U.CORREO,
      U.CLAVE_USUARIO,
    /*  (SELECT
           LISTAGG( C.DESC_CARGO  + ' - ' ||  O.DESC_OFICINA,   ' ' || CHR(13)) WITHIN GROUP (ORDER BY UC.ID_USUARIO_CARGO)  --  ,  LISTAGG(S.DNOMBRE, ', ')   WITHIN GROUP (ORDER BY S.DDOCUMENTO)
       FROM
           SEG_D_USUARIO_CARGO UC
           INNER JOIN SEG_M_CARGO C ON C.ID_CARGO = UC.ID_CARGO
           INNER JOIN SEG_M_OFICINA O ON O.ID_OFICINA = UC.ID_OFICINA

       WHERE
           UC.ID_USUARIO = U.ID_USUARIO)*/ '' DESC_CARGO,

            U.FLG_ESTADO,
            U.USU_CREACION,       
			CONVERT(VARCHAR,U.FEC_CREACION, 103) FEC_CREACION,
            U.IP_CREACION,
            U.USU_MODIFICACION,
			CONVERT(VARCHAR,U.FEC_MODIFICACION, 103) FEC_MODIFICACION,
            U.IP_MODIFICACION


  FROM
      SEG_M_USUARIO U
        LEFT JOIN  SEG_M_ENTIDAD E ON E.ID_ENTIDAD = U.ID_ENTIDAD
GO



